### PR TITLE
Downgrade to Java 7

### PR DESCRIPTION
**Pull request by pakoito**
The library doesn't use any of the Java 8 classes or utilities. A Java 7 version downgrade makes it usable off the jar directly on Android, which is a massive Java consumer market.

I also removed the public identifier from the interfaces, as interfaces don't allow private or package encapsulation anyway.

### CODE REVIEW

**Comment by msteindorfer** [comment]
It's true that the current version of the library, is not depending on Java 8 or JDK 8, however I'm working on a redesign of the interface that is planned to require JDK 8+, will make use of functional APIs, and integrate with the Stream API. 

As far as I know, [Android N](https://developer.android.com/preview/j8-jack.html) will eventually support Java 8. @pakoito, do you thing Java 7 compatibility for Android is of importance on the longer perspective?

I could consider deploying a JDK 7 build of the current version of capsule (essentially your pull request), however for the mid and long term I'm inclined to require JDK 8+.

**Comment by pakoito** [comment]
>As far as I know, Android N will eventually support Java 8. @pakoito, do you thing Java 7 compatibility for Android is of importance on the longer perspective?

That is for minimum version starting N. Most apps current minimum version is on average supporting ICS or JellyBean, so we don't expect to be able to use Java 8 APIs in at least 4-5 years.

I would request that you don't discard all those developers just for architectural reasons.

**Comment by msteindorfer** [comment]
For now I created a separate build of a JDK 7 version of capsule (see README), which should cover your needs. I temporary forked capsule for creating the JDK 7 compatible release (+ setup for build server), but that fork should go away soon.

I'll consider to maintain a JDK 7 backport of capsule, which preferably should live in a sub-module within this repository. Don't understand this a full commitment, but I'll give it a try and see how this effort goes on the way.

**Comment by pakoito** [comment]
Many thanks.

**Pull request closed without merging**
